name: in1t Canary Build
run-name: ${{ github.actor }} fix arm33333 bug
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
