name: in1t Canary Builds
on: [push]
jobs:
  artifact:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - run: pwd
      - run: ls
      - run: pwd ${{ github.workspace }}
      - run: ls ${{ github.workspace }}
