name: in1t Canary Builds

on: [push]
jobs:
  artifact:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
