name: in1t Canary Builds

on: [push]
jobs:
  artifact:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: test
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: ${{ github.workspace }}/README.md
  
